### ISSUE TITLE
getPhoneLogs use wrong type of call log 

### ISSUE THREAD

**Issue by dolanor** [google/flutter.plugins#11]
Hi,
Today I tried to run the example code in a standard flutter emulator, and it failed with this log: 
```
E/flutter (17759): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: type 'List<dynamic>' is not a subtype of type 'Iterable<Map<String, Object>>'
E/flutter (17759): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:302:13)
E/flutter (17759): <asynchronous suspension>
E/flutter (17759): #1      PhoneLog.getPhoneLogs (package:phone_log/phone_log.dart:49:66)
E/flutter (17759): <asynchronous suspension>
E/flutter (17759): #2      _MyHomePageState.fetchCallLog (package:regord/main.dart:85:53)
E/flutter (17759): <asynchronous suspension>
E/flutter (17759): #3      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:513:14)
E/flutter (17759): #4      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:568:30)
E/flutter (17759): #5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:120:24)
E/flutter (17759): #6      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:242:9)
E/flutter (17759): #7      TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:204:7)
E/flutter (17759): #8      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
E/flutter (17759): #9      _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:20)
E/flutter (17759): #10     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:192:22)
E/flutter (17759): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:149:7)
E/flutter (17759): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:101:7)
E/flutter (17759): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:85:7)
E/flutter (17759): #14     _rootRunUnary (dart:async/zone.dart:1136:13)
E/flutter (17759): #15     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter (17759): #16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
E/flutter (17759): #17     _invoke1 (dart:ui/hooks.dart:223:10)
E/flutter (17759): #18     _dispatchPointerDataPacket (dart:ui/hooks.dart:144:5)
```
After a lot of investigation, it seems the invokeMethod doesn't really return what it should in its guts.

**Comment by mehmetf** [comment]
Fixed by https://github.com/google/flutter.plugins/pull/15

Sorry it took this long. We have better processes to monitor the code health in this repo now.
