### ISSUE TITLE
Exception on loading from byte data

### ISSUE THREAD

**Issue by S-Man42** [google/flutter.plugins#126]
I get following exception, when I try to load an audio file from byte data:

```
I/AudiofileplayerPlugin( 4354): onMethodCall: method = load
E/MediaPlayerNative( 4354): error (1, -2147483648)
E/flutter ( 4354): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(AudioPluginError, Could not create ManagedMediaPlayer:Prepare failed.: status=0x1, null, null)
E/flutter ( 4354): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
E/flutter ( 4354): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167:18)
E/flutter ( 4354): <asynchronous suspension>
E/flutter ( 4354): #2      Audio._sendMethodCall (package:audiofileplayer/audiofileplayer.dart:751:7)
E/flutter ( 4354): <asynchronous suspension>
E/flutter ( 4354): #3      Audio._load (package:audiofileplayer/audiofileplayer.dart:433:7)
E/flutter ( 4354): <asynchronous suspension>
E/flutter ( 4354): 
```

Could you please have a look if I am using the plugin correctly? I am not quite sure about it.

My Widget:

```
class GCWSoundPlayer extends StatefulWidget {
  final PlatformFile file;
  final bool showMetadata;

  const GCWSoundPlayer({Key key, @required this.file, this.showMetadata: false}) : super(key: key);

  @override
  _GCWSoundPlayerState createState() => _GCWSoundPlayerState();
}

class _GCWSoundPlayerState extends State<GCWSoundPlayer> {

  Audio audio;
  var isPlaying = false;
  var isLoaded = false;

  double totalSeconds;
  double currentPosition;

  @override
  void initState() {
    super.initState();
  }

  @override
  void dispose() {
    audio
      ..pause()
      ..dispose();
    super.dispose();
  }

  _audioPause() {
    if (audio == null)
      return;

    audio.pause();
    isPlaying = false;
  }

  _onDurationSet(double durationSeconds) {
    totalSeconds = durationSeconds;
    setState(() {
      isLoaded = true;
    });

    audio.play();
    isPlaying = true;
  }

  _onPositionUpdated(double positionSeconds) {
    currentPosition = positionSeconds;
    setState(() {});
  }

  _audioLoad() {
    audio = Audio.loadFromByteData(widget.file.bytes.buffer.asByteData(),
        // // Called when audio has finished playing.
        // onComplete: () => _handleOnComplete(),
        // Called when audio has loaded and knows its duration.
        onDuration: (double durationSeconds) => _onDurationSet(durationSeconds),
        // Called repeatedly with updated playback position.
        onPosition: (double positionSeconds) => _onPositionUpdated(positionSeconds)
    );
  }

  _audioPlay() {
    if (!isLoaded) {
      _audioLoad();
    } else {
      audio.resume();
      isPlaying = true;
    }
  }

  _audioStop() {
    if (audio == null)
      return;

    audio.pause();
    audio.dispose();

    isPlaying = false;
    isLoaded = false;
  }

  @override
  Widget build(BuildContext context) {
    return Row(
      children: [
        GCWIconButton(
          iconData: isPlaying ? Icons.pause : Icons.play_arrow,
          onPressed: isPlaying
              ? () => _audioPause()
              : () => _audioPlay(),
        ),
        GCWIconButton(
          iconData: Icons.stop,
          onPressed: () => _audioStop()
        ),
        if (widget.showMetadata)
        Expanded(
          child: Container(
              child: Column(
                children: [
                  Row(
                    children: [
                      Expanded(
                        child: GCWText(
                            text: widget.file.name,
                            style: gcwTextStyle()
                                .copyWith(fontWeight: FontWeight.bold, color: themeColors().dialogText())),
                      ),
                    ],
                  )
                ],
              ),
              color: themeColors().accent(),
              padding: EdgeInsets.all(DOUBLE_DEFAULT_MARGIN)),
        ),
       Expanded(
         child: GCWSlider(value: 0.0, min: 0.0, max: totalSeconds ?? 100.0, suppressReset: true),
       ),
       GCWText(text: _durationText())
      ],
    );
  }

  _durationText() {
    var total = '--:--';
    if (totalSeconds != null && totalSeconds >= 0) {
      var min = (totalSeconds / 60).floor();
      var sec = (totalSeconds % 60).floor();
      total = min.toString().padLeft(2, '0') + ':' + sec.toString().padLeft(2, '0');
    }

    var position = '--:--';
    if (currentPosition != null && currentPosition >= 0) {
      var min = (currentPosition / 60).floor();
      var sec = (currentPosition % 60).floor();
      position = min.toString().padLeft(2, '0') + ':' + sec.toString().padLeft(2, '0');
    }

    return '$position / $total';
  }
}
```

**Comment by monkeyswarm** [comment]
What is the OS, Version, and device? Also attach the audio file in question, I suspect it may be of an unsupported format.

You can also test this by running the example app, and swapping in your sound file to see if it works.

**Comment by S-Man42** [comment]
Android Emulator: Pixel 3 API 30, Target: Android 11.0 (Google Play). It's an mp3 file.

Since this is from byte data (the file is part of bigger file container) it is hard to give you the file. But I can assure you, that it worked with another plugin. I just want to use yours because you wrote, you support reading from byte data also on iOS, which the other plugin doesn't. I can extracted it and saved it as a mp3 file, but then it's no pure byte data anymore... You'll need to convert it before using (need to put it into a zip archive bc GitHub doesn't support mp3 attachments)
[sound.zip](https://github.com/google/flutter.plugins/files/8043151/sound.zip)


The important thing for me is: Reading from Byte Data without creating a local file. It shall work on Android and iOS. That's why I choose your lib.

It is very hard for me to use your example app, because you put every case into one class. I am not very familiar with your plugin at the moment, so it's hard to identify the parts, I personally need. That's why I'd like to ask you to check my code. I believe I added everything necessary. But I really don't know. Please have a look at it.

**Comment by monkeyswarm** [comment]
The emulator behaves differently than hardware. What happens on an actual hardware device?

**Comment by pascaaaal** [comment]
Same Error here, I read my mp3 file from a sqlite database. When loading it directly from the assets it works, but when loading it from my database the error occurs. I checked the IOS logs and it says that the file format is unsupported. The weird thing is that loading the same file from the assets works just fine. Even converting the asset data to a UInt8List and back works. 

On Android loading the data from the database works fine.
