### ISSUE TITLE
Crash while playing audio

### ISSUE THREAD

**Issue by SaadArdati** [google/flutter.plugins#54]
```
E/AndroidRuntime( 6676): java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime( 6676): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:148)
E/AndroidRuntime( 6676): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error(MethodChannel.java:239)
E/AndroidRuntime( 6676): 	at com.google.flutter.plugins.audiofileplayer.AudiofileplayerPlugin.lambda$onLoad$1$AudiofileplayerPlugin(AudiofileplayerPlugin.java:296)
E/AndroidRuntime( 6676): 	at com.google.flutter.plugins.audiofileplayer.-$$Lambda$AudiofileplayerPlugin$A6LKsuboaeEM7gfQPisQG3fhlSg.onRemoteLoadComplete(Unknown Source:11)
E/AndroidRuntime( 6676): 	at com.google.flutter.plugins.audiofileplayer.RemoteManagedMediaPlayer.onError(RemoteManagedMediaPlayer.java:113)
E/AndroidRuntime( 6676): 	at android.media.MediaPlayer$EventHandler.handleMessage(MediaPlayer.java:3461)
E/AndroidRuntime( 6676): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime( 6676): 	at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime( 6676): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/AndroidRuntime( 6676): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 6676): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime( 6676): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
I/Process ( 6676): Sending signal. PID: 6676 SIG: 9

```

**Comment by monkeyswarm** [comment]
Do you have steps to reproduce?

**Comment by SaadArdati** [comment]
It seems that rapidly changing remote audio (pausing, disposing, then making a new one) causes this. Let me know if you can reproduce this.

**Comment by monkeyswarm** [comment]
Please send sample code if you have it

**Comment by SaadArdati** [comment]
```dart
    if (_remoteAudio != null) {
      await _remoteAudio.pause();
      await _remoteAudio.dispose();
      AudioSystem.instance.stopBackgroundDisplay();
    }

    _remoteAudio = Audio.loadFromRemoteUrl(track.firebaseURL, playInBackground: true, onDuration: (double duration) async {
...
```
if i run that code several times, it doesn't do well. You could argue that I should wait for the last future to finish before running the new one, but that isn't responsive to a user's experience.

**Comment by SaadArdati** [comment]
It seems that just destroying and creating new audio simply isn't handled well. Audio loading should be a cancellable task.

What happened was, after triggering several audio tracks consecutively, the plugin starts one, runs it, then the second loads and runs that (ignoring that the first should've been paused and disposed mid-load), and keeps going loading and changing and loading and changing.

If you do it fast enough, it crashes with the above error.

Although this code isn't super relevant as it requires my project's code for context, here is the full method:

```dart
  @override
  playTrack(AbstractTrack track) async {
    if (track.firebaseURL == null) return;

    setTrack(track);
    setPlayerState(ChaChaPlayerState.LOADING);

    if (_remoteAudio != null) {
      await _remoteAudio.pause();
      await _remoteAudio.dispose();
      AudioSystem.instance.stopBackgroundDisplay();
    }

    _remoteAudio = Audio.loadFromRemoteUrl(track.firebaseURL, playInBackground: true, onDuration: (double duration) async {
      this.duration = duration;
      _durationController.add(duration);
      setPlayerState(ChaChaPlayerState.PLAYING);
      _remoteAudio.resume();

      AudioSystem.instance.setMetadata(AudioMetadata(
          id: track.trackID,
          title: track.trackName,
          artist: track.artistName,
          durationSeconds: track.duration.toDouble(),
          artBytes: await networkImageToByte(track.fullCoverURL)));
      AudioSystem.instance.setSupportedMediaActions(
          <MediaActionType>{MediaActionType.playPause, MediaActionType.next, MediaActionType.previous, MediaActionType.seekTo});
      AudioSystem.instance.setAndroidNotificationButtons([
        AndroidMediaButtonType.previous,
        AndroidMediaButtonType.pause,
        AndroidMediaButtonType.next,
      ]);
    }, onPosition: (double pos) {
      double realPos = pos;
      if (track.clipEnd != -1 && track.clipEnd > track.clipStart && pos > track.clipEnd) _remoteAudio.pause();

      if (track.clipEnd != -1 && track.clipEnd > track.clipStart && pos < track.clipStart) {
        realPos = track.clipStart.toDouble();
        seek(realPos);
      }
      this.position = realPos;
      _positionController.add(realPos);
      AudioSystem.instance.setPlaybackState(true, realPos);
    }, onComplete: () {
      if (getFirebase().getTracks().indexOf(track) < getFirebase().getTracks().length - 1)
        playTrack(getFirebase().getTracks()[getFirebase().getTracks().indexOf(track) + 1]);
      else if (loop) playTrack(getFirebase().getTracks()[0]);
    }, onError: (String message) {
      _remoteAudio.dispose();
      _remoteAudio = null;
      setPlayerState(ChaChaPlayerState.STOPPED);
    });

    if (_remoteAudio == null) {
      setPlayerState(ChaChaPlayerState.STOPPED);
    }
  }
```

**Comment by volgin** [comment]
I saw the same problem today. After resume(), notification shows up correctly on Android device. Hitting pause button works as expected. Hitting play button after that results in this error, which causes the app to crash:

```
I/AudiofileplayerPlugin(26038): onMethodCall: method = pause
E/MediaPlayerNative(26038): pause called in state 8, mPlayer(0x8af7e380)
E/MediaPlayerNative(26038): error (-38, 0)
E/MediaPlayer(26038): Error (-38,0)
D/AndroidRuntime(26038): Shutting down VM
E/AndroidRuntime(26038): FATAL EXCEPTION: main
E/AndroidRuntime(26038): Process: xxx, PID: 26038
E/AndroidRuntime(26038): java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime(26038):        at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:139)
E/AndroidRuntime(26038):        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error(MethodChannel.java:236)
E/AndroidRuntime(26038):        at com.google.flutter.plugins.audiofileplayer.AudiofileplayerPlugin.lambda$onLoad$1$AudiofileplayerPlugin(AudiofileplayerPlugin.java:306)
E/AndroidRuntime(26038):        at com.google.flutter.plugins.audiofileplayer.-$$Lambda$AudiofileplayerPlugin$A6LKsuboaeEM7gfQPisQG3fhlSg.onRemoteLoadComplete(Unknown Source:11)
E/AndroidRuntime(26038):        at com.google.flutter.plugins.audiofileplayer.RemoteManagedMediaPlayer.onError(RemoteManagedMediaPlayer.java:116)
E/AndroidRuntime(26038):        at android.media.MediaPlayer$EventHandler.handleMessage(MediaPlayer.java:3281)
E/AndroidRuntime(26038):        at android.os.Handler.dispatchMessage(Handler.java:105)
E/AndroidRuntime(26038):        at android.os.Looper.loop(Looper.java:164)
E/AndroidRuntime(26038):        at android.app.ActivityThread.main(ActivityThread.java:6694)
E/AndroidRuntime(26038):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(26038):        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
E/AndroidRuntime(26038):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:769)

```

**Comment by arodriguezgb** [comment]
Yep also getting this issue if I
 rapidly press play and pause.

**Comment by volgin** [comment]
Now I am getting the same error even without pressing any buttons: just switching from one recording to the next.

It seems like this plugin has been abandoned :(

**Comment by volgin** [comment]
It appears that this issue can be resolved by adding 'await' in front of all pause() and stop() calls. While these calls are asynchronous, any call on the same audio object will result in an error, unless the previous call was allowed to complete.

**Comment by KiwiArch** [comment]
awaiting certainly helps, one other scenario this will occur in is attempting to stop and play a new audio track before the original has finished loading.  For now I'm guarding against this by forcing my play method to wait until the callback to onDuration has been made, open to better approaches?

**Comment by mr-mmmmore** [comment]
This is the crash I see the most on Google play. The stack track is almost the same:

```
java.lang.IllegalStateException: 
  at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply (DartMessenger.java:35)
  at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error (MethodChannel.java:14)
  at com.google.flutter.plugins.audiofileplayer.AudiofileplayerPlugin.lambda$onLoad$1 (AudiofileplayerPlugin.java:34)
  at com.google.flutter.plugins.audiofileplayer.AudiofileplayerPlugin.lambda$onLoad$1$AudiofileplayerPlugin (AudiofileplayerPlugin.java)
  at com.google.flutter.plugins.audiofileplayer.-$$Lambda$AudiofileplayerPlugin$Gbvdvgt56UgLn60XCEjyHDNyAwg.onRemoteLoadComplete (lambda:11)
  at com.google.flutter.plugins.audiofileplayer.RemoteManagedMediaPlayer.onError (RemoteManagedMediaPlayer.java:3)
  at android.media.MediaPlayer$EventHandler.handleMessage (MediaPlayer.java:3338)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:164)
  at android.app.ActivityThread.main (ActivityThread.java:6556)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:438)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:807)
```
I don't know what happens on the user side as no one has contacted about this problem yet.

**Comment by mr-mmmmore** [comment]
I can reproduce the problem with my test devices and it is as @SwissCheese5  and @arodriguezgb describe: the app crashes when I switch between two audios rapidly several times.

I have tried @KiwiArch's approach of _"forcing the play method to wait until the callback to onDuration has been made"_ but without success, actually the crashes were easier to produce, but it may be related to my own implementation.

However I have managed to completely get rid of the crash on my devices by throttling the calls to `loadFromRemoteUrl`: if a previous call was made less than 750ms before, I wait until the end of that period before actually calling the load method (750ms is short enough to stay unnoticed for normal use cases, and long enough to give time to the load method). Each new call cancels the potentially delayed previous call, so in case of a burst of calls only the last one will be executed.

I will publish a new version of my app today and see if it works with the actual users in a few weeks if the occurences of the crash decrease. I'll keep you updated.
