### ISSUE TITLE
Main screen or secondary screen for background play

### ISSUE THREAD

**Issue by spjps2009** [google/flutter.plugins#66]
Hi,

Can the audio player be initialized from secondary screen such as main->screen2 or does it have to be done on the first screen. Reason is I am having issues with background play and receiving errors like the below when pressing home button from secondary screen and im guessing this may be the issue. This however doesnt happen on the example app where it continues to play. Any help would be appreciated. Thanks!

Error:
`
E/AndroidRuntime(24856): java.lang.NoSuchMethodError: No static method putVersionedParcelable(Landroid/os/Bundle;Ljava/lang/String;Landroidx/versionedparcelable/VersionedParcelable;)V in class Landroidx/versionedparcelable/ParcelUtils; or its super classes (declaration of 'androidx.versionedparcelable.ParcelUtils' appears in /data/app/com.example.danda-Ti-9fcbCHWVzNlyasfot4w==/base.apk)
E/AndroidRuntime(24856): 	at android.support.v4.media.session.MediaSessionCompat$Callback$MediaSessionCallbackApi21.onCommand(MediaSessionCompat.java:1472)
E/AndroidRuntime(24856): 	at android.media.session.MediaSession$CallbackMessageHandler.handleMessage(MediaSession.java:1575)
E/AndroidRuntime(24856): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(24856): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime(24856): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/AndroidRuntime(24856): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(24856): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AndroidRuntime(24856): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
I/Process (24856): Sending signal. PID: 24856 SIG: 9
`

Logcat:
`
    Process: com.example.danda, PID: 24856
    java.lang.NoSuchMethodError: No static method putVersionedParcelable(Landroid/os/Bundle;Ljava/lang/String;Landroidx/versionedparcelable/VersionedParcelable;)V in class Landroidx/versionedparcelable/ParcelUtils; or its super classes (declaration of 'androidx.versionedparcelable.ParcelUtils' appears in /data/app/com.example.danda-Ti-9fcbCHWVzNlyasfot4w==/base.apk)
        at android.support.v4.media.session.MediaSessionCompat$Callback$MediaSessionCallbackApi21.onCommand(MediaSessionCompat.java:1472)
        at android.media.session.MediaSession$CallbackMessageHandler.handleMessage(MediaSession.java:1575)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
`

`
2020-04-17 12:59:50.388 24979-24979/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.danda, PID: 24979
    java.lang.RuntimeException: Unable to start service com.google.flutter.plugins.audiofileplayer.AudiofileplayerService@f2f9ae9 with null: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Intent.getAction()' on a null object reference
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4105)
        at android.app.ActivityThread.access$1800(ActivityThread.java:219)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1891)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Intent.getAction()' on a null object reference
        at com.google.flutter.plugins.audiofileplayer.AudiofileplayerService.onStartCommand(AudiofileplayerService.java:96)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4087)
        at android.app.ActivityThread.access$1800(ActivityThread.java:219) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1891) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
`

**Comment by monkeyswarm** [comment]
What type of device and what Android OS version are you on?

**Comment by spjps2009** [comment]
I tried on android emulator android version 10 plus also another device android version 7.1.1

the example app works perfectly on the emulator btw
