### ISSUE TITLE
Crash on play after update to Android 11

### ISSUE THREAD

**Issue by phimath** [google/flutter.plugins#88]
I'm getting this crash when playing audio after updating to Android 11:

```
java.lang.RuntimeException: Unable to create service com.ryanheise.audioservice.AudioService: java.lang.ClassNotFoundException: Didn't find class "com.ryanheise.audioservice.AudioService" on path: DexPathList[[zip file "/data/app/~~qwTN_ctB0CR8D8eF_XQa1Q==/com.example.stutter-hud8-N6w2IXX06yIeFsqMw==/base.apk"],nativeLibraryDirectories=[/data/app/~~qwTN_ctB0CR8D8eF_XQa1Q==/com.example.stutter-hud8-N6w2IXX06yIeFsqMw==/lib/x86, /data/app/~~qwTN_ctB0CR8D8eF_XQa1Q==/com.example.stutter-hud8-N6w2IXX06yIeFsqMw==/base.apk!/lib/x86, /system/lib, /system_ext/lib, /product/lib]]
E/AndroidRuntime( 7781): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4204)
E/AndroidRuntime( 7781): 	at android.app.ActivityThread.access$1500(ActivityThread.java:237)
E/AndroidRuntime( 7781): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1932)
E/AndroidRuntime( 7781): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime( 7781): 	at android.os.Looper.loop(Looper.java:223)
E/AndroidRuntime( 7781): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/AndroidRuntime( 7781): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 7781): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime( 7781): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/AndroidRuntime( 7781): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.ryanheise.audioservice.AudioService" on path: DexPathList[[zip file "/data/app/~~qwTN_ctB0CR8D8eF_XQa1Q==/com.example.stutter-hud8-N6w2IXX06yIeFsqMw==/base.apk"],nativeLibraryDirectories=[/data/app/~~qwTN_ctB0CR8D8eF_XQa1Q==/com.example.stutter-hud8-N6w2IXX06yIeFsqMw==/lib/x86, /data/app/~~qwTN_ctB0CR8D8eF_XQa1Q==/com.example.stutter-hud8-N6w2IXX06yIeFsqMw==/base.apk!/lib/x86, /system/lib, /system_ext/lib, /product/lib]]
E/AndroidRuntime( 7781): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
E/AndroidRuntime( 7781): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime( 7781): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime( 7781): 	at android.app.AppComponentFactory.instantiateService(AppComponentFactory.java:129)
E/AndroidRuntime( 7781): 	at androidx.core.app.CoreComponentFactory.instantiateService(CoreComponentFactory.java:66)
E/AndroidRuntime( 7781): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4183)
E/AndroidRuntime( 7781): 	... 8 more
```

**Comment by arodriguezgb** [comment]
Hey @phimath that crash is not for this Plugin. That crash should go on the AudioService repo, this repo is for AudioFilePlayer.
