### ISSUE TITLE
PlatformException Called play on an unloaded player

### ISSUE THREAD

**Issue by wellbranding** [google/flutter.plugins#90]
I am experiencing this issue in the IOS platform. Tested on IOS 12-14 and the issue is very random. I am loading multiple players at once and some of them immediately raise the following exception after I try **to play it**.

Unhandled Exception: PlatformException(AudioPluginError, Called play on an unloaded player: ab8c017a-e614-476a-9704-a3df5a65b3dc, null, null)

#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:582:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:18)
<asynchronous suspension>
#2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
#3      Audio._sendMethodCall (package:audiofileplayer/audiofileplayer.dart:751:32)
#4      Audio._playNative (package:audiofileplayer/audiofileplayer.dart:661:13)
#5      Audio._playHelper (package:audiofileplayer/audiofileplayer.dart:556:11)
#6      Audio.resume (package:audiofileplayer/audiofileplayer.dart:533:11)

**Comment by ismailslmnv** [comment]
Have you find a solution for this? Facing the same issue

**Comment by monkeyswarm** [comment]
Do you have sample code?

In theory, you should be able to call load and play (in a row, syncronously) without waiting for the load to complete. However, does awaiting the load make this issue go away?
